eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Start ssh-agent if not running
if [[ -z "$SSH_AUTH_SOCK" ]]; then
  eval "$(ssh-agent -s)" > /dev/null
fi

# GPG agent
if command -v gpgconf >/dev/null; then
  export GPG_TTY=$(tty)
fi

